a
No exception
b
Uncaught exception Backtrace_slots.Error("b")
Raised at Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 16-32
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.g in file "backtrace_slots.ml", line 44, characters 4-11
Re-raised at Backtrace_slots.g in file "backtrace_slots.ml", line 46, characters 62-71
Called from Backtrace_slots.run in file "backtrace_slots.ml", line 51, characters 11-23
Uncaught exception Backtrace_slots.Error("c")
Raised at Backtrace_slots.g in file "backtrace_slots.ml", line 47, characters 20-37
Called from Backtrace_slots.run in file "backtrace_slots.ml", line 51, characters 11-23
Uncaught exception Backtrace_slots.Error("d")
Raised at Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 16-32
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 40, characters 42-53
Called from Backtrace_slots.g in file "backtrace_slots.ml", line 44, characters 4-11
Called from Backtrace_slots.run in file "backtrace_slots.ml", line 51, characters 11-23
Uncaught exception Invalid_argument("index out of bounds")
Raised by primitive operation at Backtrace_slots.run in file "backtrace_slots.ml", line 51, characters 14-22
